### ISSUE TITLE
本书所有的代码集合 連結已失效

### ISSUE THREAD

**Issue by shengchiliu** [21-projects-for-deep-learning/MyBook#1]
本书所有的代码集合 連結已失效 煩請更新！

**Comment by shengchiliu** [comment]
https://free.com.tw/baidu-pan-blocks-taiwan-ip/

**Comment by VictorZhang2014** [comment]
你好，请问哪个链接失效了？

**Comment by VictorZhang2014** [comment]
<img width="764" alt="WX20200711-115052@2x" src="https://user-images.githubusercontent.com/6853884/87215817-ccea1a80-c36c-11ea-87d3-55efc14d5707.png">

本书所有的代码集合链接是有效的，请查看下哦
链接: https://pan.baidu.com/s/1C6waPKRlRfQ_Dj8MDatdEg 提取码: eu3k

**Comment by VictorZhang2014** [comment]
如果百度网盘不能下载，可以直接下载本项目，其中Python Code.zip就是所有的源代码
